name: Deploy PHP Application to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        # Navigate to the application directory
        cd /path/to/your/php/application

        # Pull the latest changes from GitHub
        git pull origin main

        # Restart the web server (if necessary)
        sudo systemctl restart apache2 || sudo systemctl restart httpd
        EOF
