name: CI/CD for PHP Application

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up PHP environment
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Adjust based on your PHP version
        extensions: mbstring, intl, curl, mysql

    # Step 3: Install dependencies (if using Composer)
    - name: Install Dependencies
      run: |
        if [ -f composer.json ]; then
          composer install --no-dev --optimize-autoloader
        fi

    # Step 4: Run tests
    - name: Run Tests
      run: |
        if [ -f phpunit.xml ]; then
          ./vendor/bin/phpunit
        else
          echo "No tests found, skipping."
        fi

    # Step 5: Deploy to EC2
    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "${EC2_KEY}" | base64 -d > ec2_key.pem
        chmod 600 ec2_key.pem
        scp -o StrictHostKeyChecking=no -i ec2_key.pem -r ./* $EC2_USER@$EC2_HOST:/var/www/html/
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem $EC2_USER@$EC2_HOST "sudo systemctl restart apache2"
