name: Deploy to AWS EC2
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install SonarQube Scanner
      - name: Install SonarQube Scanner
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk curl unzip
          curl -fsSL -o sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner.zip -d $HOME
          export PATH="$HOME/sonar-scanner-4.8.0.2856-linux/bin:$PATH"
          echo $PATH # Debugging to ensure the path is updated
          sonar-scanner --version # Verify installation

      # Step 3: Analyze Code with SonarQube
      - name: Analyze Code with SonarQube
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
        run: |
          export PATH="$HOME/sonar-scanner-4.8.0.2856-linux/bin:$PATH"
          sonar-scanner \
          -Dsonar.projectKey=your-project-key \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_LOGIN

      # Step 4: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            
            sudo mkdir -p /var/www/devops.sphinxworldbiz.net
            sudo cp -r * /var/www/html/
            sudo chown -R www-data:www-data /var/www/devops.sphinxworldbiz.net
            sudo systemctl restart apache2
