name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Analyze Code with SonarQube
        run: |
          sonar-scanner \
          -Dsonar.projectKey=your-project-key \
          -Dsonar.host.url=https://sonarqube-url \
          -Dsonar.login=your-token

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            sudo rm -rf /var/www/html/*
            sudo mkdir -p /var/www/html
            echo "$GITHUB_WORKSPACE" # For Debugging
            sudo cp -r * /var/www/html/
            sudo chown -R www-data:www-data /var/www/html/
            sudo systemctl restart apache2
