jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Install Sonar Scanner
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
        unzip sonar-scanner-cli-4.8.0.2856-linux.zip
        mv sonar-scanner-4.8.0.2856-linux /usr/local/sonar-scanner
        echo 'export PATH=$PATH:/usr/local/sonar-scanner/bin' >> $GITHUB_ENV

    - name: Run Sonar Scanner
      run: sonar-scanner
      env:
        SONAR_HOST_URL: "https://http://192.168.3.38:9000"
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
